repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8